name: deploy to production (aserto.de)

on:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: website/production
      url: https://aserto.de

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install npm dependencies
        working-directory: frontend
        run: npm ci

      - name: Run build task
        working-directory: frontend
        run: npm run build

      - name: Copy htaccess file
        working-directory: frontend
        run: mv .htaccess out/htaccess

      - name: Deploy to Server
        uses: mdallasanta/ssh-scp-deploy@v1.0.4
        with:
          local: "./frontend/out/*"
          remote: "~/www/asertoWeb/"
          host: ${{secrets.DEPLOY_HOST}}
          port: ${{secrets.DEPLOY_PORT}}
          user: ${{secrets.DEPLOY_USERNAME}}
          password: ${{secrets.DEPLOY_PASSWORD}}
          pre_upload: rm -r ~/www/asertoWeb/*
          post_upload: mv ~/www/asertoWeb/htaccess ~/www/asertoWeb/.htaccess
