name: deploy to dev (new.aserto.de)

on:
  push:
    branches:
      - dev
    paths:
      - frontend/**
      - .github/workflows/deploy-to-dev.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: website/dev
      url: https://new.aserto.de

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Install npm dependencies
        working-directory: frontend
        run: npm ci

      - name: Set dev robots txt
        working-directory: frontend
        run: mv public/robots.dev.txt public/robots.txt

      - name: Run build task
        working-directory: frontend
        run: npm run build
        env:
          BACKEND_USER: ${{secrets.BACKEND_USER}}
          BACKEND_PASSWORD: ${{secrets.BACKEND_PASSWORD}}

      - name: install rsync
        run: sudo apt-get install sshpass rsync

      - name: Upload with rsync
        working-directory: frontend/out
        run: sshpass -p $DEPLOY_PASSWORD rsync . $DEPLOY_USERNAME@$DEPLOY_HOST:/home/www/NewAsertoWeb -avz --delete -e "ssh -l web71 -o StrictHostKeyChecking=no"
        env:
          DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
          DEPLOY_PASSWORD: ${{secrets.DEPLOY_PASSWORD}}
          DEPLOY_USERNAME: ${{secrets.DEPLOY_USERNAME}}
