name: deploy cms (cms.aserto.de)

on:
  push:
    branches:
      - main
      - dev
    paths:
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: cms/production
      url: https://cms.aserto.de

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          dev: no
          args: --working-dir backend

      - name: Make htaccess file uploadable
        working-directory: backend
        run: mv .htaccess htaccess

      - name: Deploy to Server
        uses: mdallasanta/ssh-scp-deploy@v1.0.4
        with:
          local: "./backend/*"
          remote: "~/www/CmsAsertoWeb/"
          host: ${{secrets.DEPLOY_HOST}}
          port: ${{secrets.DEPLOY_PORT}}
          user: ${{secrets.DEPLOY_USERNAME}}
          password: ${{secrets.DEPLOY_PASSWORD}}
          pre_upload: rm -r ~/www/CmsAsertoWeb/*
          post_upload: mv ~/www/CmsAsertoWeb/htaccess ~/www/CmsAsertoWeb/.htaccess
