name: deploy cms (cms.aserto.de)

on:
  push:
    branches:
      - main
      - dev
    paths:
      - backend/**
      - .github/workflows/deploy-cms.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: cms/production
      url: https://cms.aserto.de

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          php_extensions: gd
          dev: no
          args: --working-dir backend

      - name: Create .env file
        working-directory: backend
        run: echo "INSTAGRAM_CLIENT_SECRET=${INSTAGRAM_CLIENT_SECRET}" >> .env
        env:
          INSTAGRAM_CLIENT_SECRET: ${{secrets.INSTAGRAM_CLIENT_SECRET}}

      - name: install rsync
        run: sudo apt-get install sshpass rsync

      - name: Upload with rsync
        working-directory: backend
        run: sshpass -p $DEPLOY_PASSWORD rsync . web71@s114.goserver.host:/home/www/CmsAsertoWeb --exclude-from=.deployignore --dry-run -avz --delete -e "ssh -l web71 -o StrictHostKeyChecking=no"
        env:
          DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
          DEPLOY_PASSWORD: ${{secrets.DEPLOY_PASSWORD}}
          DEPLOY_USERNAME: ${{secrets.DEPLOY_USERNAME}}
