name: deploy to dev (new.aserto.de)

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Move to frontend folder
        run: cd frontend

      - name: Install npm dependencies
        run: npm ci

      - name: Set dev robots txt
        run: mv public/robots.dev.txt public/robots.txt

      - name: Run build task
        run: npm run build

      - name: Copy htaccess file
        run: mv .htaccess out/htaccess

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          production_environment: false
          environment: website/dev

      - name: Deploy to dev Server
        uses: mdallasanta/ssh-scp-deploy@v1.0.4
        with:
          local: "./out/*"
          remote: "~/www/NewAsertoWeb/"
          host: ${{secrets.DEPLOY_HOST}}
          port: ${{secrets.DEPLOY_PORT}}
          user: ${{secrets.DEPLOY_USERNAME}}
          password: ${{secrets.DEPLOY_PASSWORD}}
          pre_upload: rm -r ~/www/NewAsertoWeb/*
          post_upload: mv ~/www/NewAsertoWeb/htaccess ~/www/NewAsertoWeb/.htaccess

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          state: "success"
          target_url: "https://new.aserto.de"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          state: "failure"
          target_url: "https://new.aserto.de"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
